version: '2'

# based off compose-sample-2, only we build nginx.conf into image
# uses sample site from https://startbootstrap.com/template-overviews/agency/

services:
  #  web:
  #    image: php:7.4-apache
  #    ports:
  #      - '80:80'


  symfony:
    build: .
    container_name: sf
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - ./isubat-app:/var/www/html
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    container_name: mysql_isubat
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${SYMFONY_DB_NAME}
      MYSQL_USER: ${SYMFONY_DB_USER}
      MYSQL_PASSWORD: ${SYMFONY_DB_PATH}
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${SYMFONY_DB_NAME}
      MYSQL_USER: ${SYMFONY_DB_USER}
      MYSQL_PASSWORD: ${SYMFONY_DB_PATH}
    ports:
      - "8080:80"

volumes:
  db_data: